// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0EwqFBkNotPxYl2CjmoofvdLFdlhPaM8',
    appId: '1:878749524368:web:3441607d6294184b385315',
    messagingSenderId: '878749524368',
    projectId: 'fir-testing-ad65b',
    authDomain: 'fir-testing-ad65b.firebaseapp.com',
    storageBucket: 'fir-testing-ad65b.appspot.com',
    measurementId: 'G-38ZDKNNH6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR0Tjf5Bswr6rgPTtKIgh48F7snxieyxA',
    appId: '1:878749524368:android:6051801b67e7fb1a385315',
    messagingSenderId: '878749524368',
    projectId: 'fir-testing-ad65b',
    storageBucket: 'fir-testing-ad65b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjVV0XqUwkVJtiA2sM8lDXik3n1EXaPxg',
    appId: '1:878749524368:ios:f4ccb9df29674e36385315',
    messagingSenderId: '878749524368',
    projectId: 'fir-testing-ad65b',
    storageBucket: 'fir-testing-ad65b.appspot.com',
    iosClientId: '878749524368-reaaedkb9nd9giqig4thtauogoocmm68.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjVV0XqUwkVJtiA2sM8lDXik3n1EXaPxg',
    appId: '1:878749524368:ios:f6d8713401beecda385315',
    messagingSenderId: '878749524368',
    projectId: 'fir-testing-ad65b',
    storageBucket: 'fir-testing-ad65b.appspot.com',
    iosClientId: '878749524368-6fc3ofojg73raf9k573e0vbhk26jm7up.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
